zsh, git/git-myremote: Move remote address into environment

diff --git a/dotfile/common/git/bin/git-myremote b/dotfile/common/git/bin/git-myremote
--- a/dotfile/common/git/bin/git-myremote
+++ b/dotfile/common/git/bin/git-myremote
@@ -4,10 +4,8 @@
 
 set -eu
 
-DEST="git@git.ksrv.home"
-
 usage() {
-    die "usage: ${0##*/} desc|help|list|info|init [arg ...]"
+    die "usage: ${0##*/} [-a address] desc|help|list|info|init [arg ...]"
 }
 
 die() {
@@ -18,6 +16,21 @@ die() {
 }
 
 main() {
+    addr="${GIT_MYREMOTE_ADDR:-}"
+    while getopts "a:h" opt; do
+        case "${opt}" in
+            a) addr="${OPTARG}" ;;
+            h | ?) usage ;;
+        esac
+    done
+    shift $((OPTIND - 1))
+
+    if [ -z "${addr}" ]; then
+        echo "Set environment variable GIT_MYREMOTE_ADDR or use \
+'-a address' option to set the remote address." 1>&2
+        die "error: addr not set"
+    fi
+
     if [ "$#" -lt 1 ]; then
         usage
     fi
@@ -35,7 +48,7 @@ main() {
         args="${args} '${arg}'"
     done
 
-    ssh "${DEST}" -- "${command}" "${args}"
+    ssh "${addr}" -- "${command}" "${args}"
 }
 
 main "$@"
